<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Accounting\Module'                        => __DIR__ . '/Module.php',
    'Accounting\Controller\QuickbooksController' => __DIR__ . '/src/Accounting/Controller/QuickbooksController.php',
    'AccountingTest\Framework\TestCase'        => __DIR__ . '/tests/Accounting/Framework/TestCase.php',
    'AccountingTest\SampleTest'                => __DIR__ . '/tests/Accounting/SampleTest.php',
);
