<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate(\Application\Controller\IndexController::APP_TITLE))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>
            
            <link rel="apple-touch-icon" sizes="57x57"
	href="/img/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60"
	href="/img/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72"
	href="/img/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76"
	href="/img/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114"
	href="/img/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120"
	href="/img/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144"
	href="/img/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152"
	href="/img/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180"
	href="/img/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"
	href="/img/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32"
	href="/img/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96"
	href="/img/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16"
	href="/img/favicon-16x16.png">

<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
<link href="/vendors/dropzone/dist/min/dropzone.min.css"
	rel="stylesheet">
<!-- Le styles -->
<link
	href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css"
	rel="stylesheet" />
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->
        // ->prependStylesheet($this->basePath('ui/dropdown.min.css'))
        // ->prependStylesheet($this->basePath('chosen/chosen.css'))
        prependStylesheet($this->basePath('css/wasabi.gritter.css'))
            ->prependStylesheet($this->basePath('css/wasabi.modal.css'))
            ->prependStylesheet($this->basePath('css/wasabi.suggest.css'))
            ->prependStylesheet($this->basePath('css/wasabi.wizard.css'))
            ->prependStylesheet($this->basePath('css/icheck/flat/green.css'))
            ->prependStylesheet($this->basePath('css/custom.css'))
            ->prependStylesheet($this->basePath('css/animate.min.css'))
            ->prependStylesheet($this->basePath('fonts/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))?>
          

        <!-- Scripts -->
        <?php
        
        echo $this->headScript()
            ->prependFile($this->basePath('/js/vue.js'))
            ->prependFile($this->basePath('js/bootstrap-pincode-input.js'))
            ->prependFile($this->basePath('js/jquery.mask.min.js'))
            ->prependFile($this->basePath('js/jquery.numpad.js'))
            ->prependFile($this->basePath('chosen/chosen.jquery.js'))
            ->prependFile($this->basePath('js/wasabi.gritter.js'))
            ->prependFile($this->basePath('js/wasabi.suggest.js'))
            ->prependFile($this->basePath('js/wasabilib.min.js'))
            ->prependFile($this->basePath('js/nprogress.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath('js/imApp.js'))
            ->prependFile($this->basePath('angular/lib/angular.js'))?>
        
								



<script
	src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<!-- <script src="/js/vue.js"></script> -->

</head>
<body class="nav-md footer_fixed">
	<div class="container body">
		

		<div class="main_container">

			

			<!-- top navigation -->

			
			<!-- /top navigation -->

			<!-- page content -->
			<div class="right_col" role="main">

				<div class="">
					<div class="page-title">
						<div class="title_left">
							<?php // thie breadcrumbs go here ?>
						</div>

						<!-- 						<div class="title_right"> -->
						<!-- 							<div -->
						<!-- 								class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search"> -->
						<!-- 								<div class="input-group"> -->
						<!-- 									<input type="text" class="form-control" -->
						<!-- 										placeholder="Search for..."> <span class="input-group-btn"> -->
						<!-- 										<button class="btn btn-default" type="button">Go!</button> -->
						<!-- 									</span> -->
						<!-- 								</div> -->
						<!-- 							</div> -->
						<!-- 						</div> -->
					</div>
					<div class="clearfix"></div>
       
        
            <?php echo $this->content; ?>
            <?php //echo $this->partial("application_chat_popup")?>
            </div>

				<!-- footer content -->

				<!-- 				<footer> -->
				<!-- 					<div class=""> -->
				<!-- 						<p class="pull-right"> -->
				<!-- 							Powered by <a>Swoop Effects</a> -->

				<!-- 						</p> -->
				<!-- 					</div> -->
				<!-- 					<div class="clearfix"></div> -->
				<!-- 				</footer> -->
				<!-- /footer content -->
			</div>
			<!-- /page content -->

		</div>

	</div>
        <?php echo $this->inlineScript()?>
       
        

	<!-- chart js -->
	<script src="/js/chartjs/chart.min.js"></script>
	<!-- bootstrap progress js -->
	<script src="/js/progressbar/bootstrap-progressbar.min.js"></script>
	<script src="/js/nicescroll/jquery.nicescroll.min.js"></script>
	<!-- icheck -->
	<script src="/js/icheck/icheck.min.js"></script>

	<script src="/js/custom.js"></script>
	<script src="/vendors/validator/validator.js"></script>
	<script src="/vendors/dropzone/dist/min/dropzone.min.js"></script>





</body>

</html>
